name: JokesCitrix Proj Build

on:
  push: # 触发方式 push
    branches: [ master ]  # 执行分支 master
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  #拉取代码
    - name: Setup .NET  # 安装.net core 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies # 安装依赖项
      run: dotnet restore
    - name: Build  # build proj
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: test_CLI
      run: dotnet --version
