on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: "/home/runner/work/JokesCitrix/JokesCitrix/JokesWebApp/wwwroot/lib"
        args: >
          -Dsonar.organization=ryan1997
          -Dsonar.projectKey=Ryan1997_JokesCitrix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: "e3a3444d30ceaf9241f330db111bef14b0993af5"
